# Generated by Django 5.2.14 on 2026-05-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_location_order_delivery_charge_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
