# Generated by Django 5.2.14 on 2026-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
