# Generated by Django 5.2.3 on 2026-07-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_packaging_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.PositiveIntegerField()),
                ('is_percentage', models.BooleanField(default=True, help_text="If checked, discount is a percentage. Otherwise, it's a fixed amount (FCFA).")),
                ('points_required', models.PositiveIntegerField(default=0, help_text='Number of reward points required to use this coupon.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent_per_point', models.PositiveIntegerField(default=100, help_text='Amount in FCFA required to earn points')),
                ('points_earned', models.PositiveIntegerField(default=1, help_text='Points earned per amount spent')),
            ],
            options={
                'verbose_name': 'Reward Setting',
                'verbose_name_plural': 'Reward Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
    ]
