# Generated by Django 5.2.3 on 2026-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_rewardsetting_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsetting',
            name='max_redeemable_points',
            field=models.PositiveIntegerField(default=100, help_text='Maximum points a customer can redeem per order'),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='points_value_in_fcfa',
            field=models.PositiveIntegerField(default=10, help_text='FCFA value of 1 redeemed point (e.g. 1 point = 10 FCFA off)'),
        ),
        migrations.AlterField(
            model_name='rewardsetting',
            name='amount_spent_per_point',
            field=models.PositiveIntegerField(default=100, help_text='Amount in FCFA spent to earn 1 point'),
        ),
        migrations.AlterField(
            model_name='rewardsetting',
            name='points_earned',
            field=models.PositiveIntegerField(default=1, help_text='Points earned per threshold amount'),
        ),
    ]
