# Generated by Django 5.2.3 on 2026-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rewardsetting_max_redeemable_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardsetting',
            name='max_redeemable_points',
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='min_redeemable_points',
            field=models.PositiveIntegerField(default=50, help_text='Minimum points a customer must have before they can redeem any'),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='points_expiry_days',
            field=models.PositiveIntegerField(default=365, help_text='Number of days points are valid from the date the user first earned them. Set to 0 for no expiry.'),
        ),
    ]
