# Generated by Django 5.2.3 on 2026-10-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_rewardsetting_max_redeemable_points_and_more'),
        ('pages', '0005_branch_trainingexplanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch from which the order was placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pages.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Branch name snapshot', max_length=100),
        ),
    ]
