# Generated by Django 5.2.3 on 2026-10-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_branch_order_branch_name'),
        ('pages', '0006_marqueesetting_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsetting',
            name='branch',
            field=models.OneToOneField(blank=True, help_text='Branch for this reward setting. Leave blank for default / global setting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_setting', to='pages.branch'),
        ),
    ]
