# Generated by Django 5.2.3 on 2026-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rewardsetting_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Reward points redeemed by customer on this order'),
        ),
    ]
