# Generated by Django 5.2.3 on 2026-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_points_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('momo', 'Mobile Money'), ('points_redeemed', 'Paid with Redeemed Points')], default='cod', max_length=50),
        ),
    ]
