# Generated by Django 5.2.3 on 2026-10-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_branch_trainingexplanation_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch for the reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pages.branch'),
        ),
    ]
