# Generated by Django 5.2.3 on 2026-10-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('table', 'Table Reservation'), ('birthday', 'Birthday Surprise'), ('engagement', 'Engagement Surprise'), ('event', 'General Event'), ('other', 'Other Reservation')], default='table', max_length=20),
        ),
    ]
