# Generated by Django 5.2.3 on 2026-10-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_madeoncommanditem_madeoncommandinquiry'),
        ('pages', '0005_branch_trainingexplanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this category is offered. Leave empty to show in ALL branches.', related_name='categories', to='pages.branch'),
        ),
        migrations.AddField(
            model_name='meal',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this meal is available. Leave empty to show in ALL branches.', related_name='meals', to='pages.branch'),
        ),
        migrations.AddField(
            model_name='review',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this review is associated with (leave blank for all).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='pages.branch'),
        ),
    ]
