# Generated by Django 5.2.3 on 2026-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
