# Generated by Django 5.2.3 on 2026-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_earned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user first earned reward points. Used to calculate expiry.', null=True),
        ),
    ]
