# Generated by Django 5.2.3 on 2026-10-03 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_points_earned_at'),
        ('pages', '0006_marqueesetting_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='Total legacy points across all branches'),
        ),
        migrations.CreateModel(
            name='UserBranchReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points earned at this branch')),
                ('points_earned_at', models.DateTimeField(blank=True, help_text='Timestamp of when the user first earned reward points at this branch.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='pages.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branch Reward',
                'verbose_name_plural': 'User Branch Rewards',
                'unique_together': {('user', 'branch')},
            },
        ),
    ]
