# Generated by Django 5.2.3 on 2026-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/graduations/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_level', models.CharField(choices=[('beginner', 'Beginner Level'), ('intermediate', 'Intermediate Level'), ('advanced', 'Advanced Masterclass')], default='beginner', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Why do you want to join this training or any prior experience?')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
