# Generated by Django 5.2.3 on 2026-07-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_graduationeventimage_trainingapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text to display in the marquee bar', max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marquee Setting',
                'verbose_name_plural': 'Marquee Settings',
            },
        ),
    ]
