# Generated by Django 5.2.3 on 2026-10-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_marqueesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name, e.g. Jouvence, Bastos', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Fine Dining & Pastry Palace', max_length=200)),
                ('hero_title', models.CharField(blank=True, help_text='Custom hero heading for this branch (leave blank to use default)', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Custom hero subheading for this branch (leave blank to use default)')),
                ('address', models.CharField(default='Yaounde, Cameroon', max_length=255)),
                ('phone', models.CharField(default='+237 621 643 169', max_length=50)),
                ('email', models.EmailField(blank=True, default='hello@cakeprincess.com', max_length=254)),
                ('opening_hours', models.CharField(default='Every day from 11:00 AM', max_length=150)),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps embed iframe src or URL')),
                ('image', models.ImageField(blank=True, help_text='Representative photo of this branch', null=True, upload_to='branches/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Set as default branch when user hasn't selected one")),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional Baking & Pastry Arts Program', max_length=200)),
                ('subtitle', models.CharField(default='Empowering the next generation of master bakers, pastry artists, and culinary entrepreneurs in Cameroon.', max_length=300)),
                ('overview', models.TextField(help_text='Full in-depth explanation of the training program and training experience.')),
                ('curriculum', models.TextField(help_text='Course modules breakdown. Format: one module or section per line.')),
                ('duration_info', models.CharField(default='3 Months (Intensive) / 6 Months (Masterclass)', max_length=200)),
                ('schedule_info', models.CharField(default='Morning Sessions (9:00 AM - 1:00 PM) & Weekend Batches', max_length=200)),
                ('certification_info', models.CharField(default='Cake Princess Diplôme de Pâtisserie & Recommendation', max_length=200)),
                ('kit_included', models.CharField(default='Complete Professional Starter Pastry Kit & Branded Apron', max_length=200)),
                ('eligibility_info', models.CharField(default='Open to beginners, culinary lovers, and professional upskillers', max_length=200)),
                ('faq_text', models.TextField(blank=True, help_text='Frequently asked questions, formatted with Q: and A: or lines')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Page Explanation',
                'verbose_name_plural': 'Training Page Explanations',
            },
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where applicant wants to train', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_applications', to='pages.branch'),
        ),
        migrations.CreateModel(
            name='BranchHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branches/heroes/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='pages.branch')),
            ],
            options={
                'verbose_name': 'Branch Hero Image',
                'verbose_name_plural': 'Branch Hero Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BranchNavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='URL path, e.g. /menu/, /services/, /reservations/', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_links', to='pages.branch')),
            ],
            options={
                'verbose_name': 'Branch Nav Link',
                'verbose_name_plural': 'Branch Nav Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Short teaser for cards', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('icon', models.CharField(choices=[('cake', 'Cake & Pastry (Birthday / Celebration)'), ('truck', 'Fast Delivery'), ('sparkles', 'Surprise & Decor Planning'), ('calendar', 'Event & Table Reservations'), ('gift', 'Gift Hampers & Corporate Packages'), ('academic', 'Culinary & Baking Training'), ('cutlery', 'Bespoke Catering & Buffet')], default='cake', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price_starting_at', models.CharField(blank=True, help_text='e.g. From 15,000 FCFA or Custom Quote', max_length=100)),
                ('features', models.TextField(blank=True, help_text='List key features, one item per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches offering this service. Leave blank to offer across ALL branches.', related_name='services', to='pages.branch')),
            ],
            options={
                'verbose_name': 'Service Offered',
                'verbose_name_plural': 'Services Offered',
                'ordering': ['order', 'title'],
            },
        ),
    ]
