# Generated by Django 5.2.3 on 2026-10-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_branch_trainingexplanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marqueesetting',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch for this marquee announcement. Leave blank to display across all branches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marquee_settings', to='pages.branch'),
        ),
    ]
